version: 0.2

phases:
  pre_build:
    commands:
      - npm ci
  build:
    on-failure: ABORT
    commands:
      - npm run build
  post_build:
    commands:
      - cd build
      - aws s3 sync . s3://jtamu-google-login-front-bucket01 --delete
      - aws cloudfront create-invalidation --distribution-id ECFH767E363LU --paths "/*"
